### ISSUE TITLE
Layout Editing Reloads Everything

### ISSUE THREAD

**Issue by encryptedTaco** [embedthis/expansive#2]
When a layout or partial is edited, because of how they work, everything in the site is regenerated. Usually, this is not a problem, however, with a large copy directory (>1GB), regenerating everything when a single file is edited becomes a problem. This brings generation times up from <1 second to >20 seconds.

**Comment by embedthis** [comment]
This issue is going to be deferred.

As partials can be invoked by script, it is not possible for expansive to know which files need to be rebuilt when a partial changes.
