### ISSUE TITLE
cannot find expansive configuration file

### ISSUE THREAD

**Issue by liuliu7616** [embedthis/expansive#40]
I have installed it successfully but when i run it ,it says : 
expansive: ERROR: Cannot find expansive configuration file
  

the system is centos  64

**Comment by mobrien** [comment]
More detail please.

What command sequence did you type?
What files are in the directory?

Can't help with this little information.

**Comment by liuliu7616** [comment]
[root@localhost expansive-0.7.1]# expansive
expansive: ERROR: Cannot find expansive configuration file
[root@localhost expansive-0.7.1]#

**Comment by mobrien** [comment]
Suggest you try the quick tour:

https://embedthis.com/expansive/doc/users/tour.html

**Comment by liuliu7616** [comment]
thank you ,i am careless
